apiVersion: v1
kind: Service
metadata:
  name: hospital-web-service
spec:
  selector:
    app: hospital-web
  type: LoadBalancer  # or ClusterIP (내부용) / NodePort (테스트용)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
